export const users = [
  {
    id: 1,
    name: { first: "Alice", last: "Johnson" },
    gender: "female",
    dob: { age: 34 },
    registered: { age: 5 },
    location: { city: "Los Angeles" },
    nat: "US",
    email: "alice.johnson@example.com",
    phone: "(555) 123-4567",
  },
  {
    id: 2,
    name: { first: "Bob", last: "Martinez" },
    gender: "male",
    dob: { age: 28 },
    registered: { age: 1 },
    location: { city: "Miami" },
    nat: "US",
    email: "bob.martinez@example.com",
    phone: "(555) 234-5678",
  },
  {
    id: 3,
    name: { first: "Carl", last: "Chen" },
    gender: "male",
    dob: { age: 41 },
    registered: { age: 10 },
    location: { city: "San Francisco" },
    nat: "CA",
    email: "carl.chen@example.ca",
    phone: "+1-604-555-7890",
  },
  {
    id: 4,
    name: { first: "Daniela", last: "Rossi" },
    gender: "female",
    dob: { age: 37 },
    registered: { age: 3 },
    location: { city: "Berlin" },
    nat: "DE",
    email: "daniela.rossi@example.de",
    phone: "+49 30 1234567",
  },
  {
    id: 5,
    name: { first: "Emily", last: "Clark" },
    gender: "female",
    dob: { age: 22 },
    registered: { age: 2 },
    location: { city: "London" },
    nat: "GB",
    email: "emily.clark@example.co.uk",
    phone: "+44 20 7946 0958",
  },
  {
    id: 6,
    name: { first: "Frank", last: "Nguyen" },
    gender: "male",
    dob: { age: 45 },
    registered: { age: 8 },
    location: { city: "Sydney" },
    nat: "AU",
    email: "frank.nguyen@example.com.au",
    phone: "+61 2 9374 4000",
  },
  {
    id: 7,
    name: { first: "Grace", last: "Kumar" },
    gender: "female",
    dob: { age: 29 },
    registered: { age: 4 },
    location: { city: "Mumbai" },
    nat: "IN",
    email: "grace.kumar@example.in",
    phone: "+91 22 2282 1234",
  },
  {
    id: 8,
    name: { first: "Hiroshi", last: "Sato" },
    gender: "male",
    dob: { age: 32 },
    registered: { age: 6 },
    location: { city: "Tokyo" },
    nat: "JP",
    email: "hiroshi.sato@example.jp",
    phone: "+81 3-1234-5678",
  },
  {
    id: 9,
    name: { first: "Isabella", last: "Martins" },
    gender: "female",
    dob: { age: 27 },
    registered: { age: 1 },
    location: { city: "São Paulo" },
    nat: "BR",
    email: "isabella.martins@example.com.br",
    phone: "+55 11 91234-5678",
  },
  {
    id: 10,
    name: { first: "Jamal", last: "Ahmed" },
    gender: "male",
    dob: { age: 39 },
    registered: { age: 7 },
    location: { city: "Cairo" },
    nat: "EG",
    email: "jamal.ahmed@example.eg",
    phone: "+20 2 2795 1234",
  },
  {
    id: 11,
    name: { first: "Katrina", last: "Lopez" },
    gender: "female",
    dob: { age: 31 },
    registered: { age: 5 },
    location: { city: "Mexico City" },
    nat: "MX",
    email: "katrina.lopez@example.mx",
    phone: "+52 55 1234 5678",
  },
  {
    id: 12,
    name: { first: "Liam", last: "O'Connor" },
    gender: "male",
    dob: { age: 26 },
    registered: { age: 2 },
    location: { city: "Dublin" },
    nat: "IE",
    email: "liam.oconnor@example.ie",
    phone: "+353 1 234 5678",
  },
  {
    id: 13,
    name: { first: "Mia", last: "Ng" },
    gender: "female",
    dob: { age: 24 },
    registered: { age: 3 },
    location: { city: "Singapore" },
    nat: "SG",
    email: "mia.ng@example.sg",
    phone: "+65 6123 4567",
  },
  {
    id: 14,
    name: { first: "Noah", last: "Smith" },
    gender: "male",
    dob: { age: 36 },
    registered: { age: 9 },
    location: { city: "Toronto" },
    nat: "CA",
    email: "noah.smith@example.ca",
    phone: "+1-416-555-0199",
  },
  {
    id: 15,
    name: { first: "Olivia", last: "Brown" },
    gender: "female",
    dob: { age: 30 },
    registered: { age: 4 },
    location: { city: "Auckland" },
    nat: "NZ",
    email: "olivia.brown@example.nz",
    phone: "+64 9-123 4567",
  },
  {
    id: 16,
    name: { first: "Pedro", last: "Fernández" },
    gender: "male",
    dob: { age: 43 },
    registered: { age: 12 },
    location: { city: "Madrid" },
    nat: "ES",
    email: "pedro.fernandez@example.es",
    phone: "+34 91 123 4567",
  },
  {
    id: 17,
    name: { first: "Quinn", last: "Taylor" },
    gender: "female",
    dob: { age: 29 },
    registered: { age: 3 },
    location: { city: "Chicago" },
    nat: "US",
    email: "quinn.taylor@example.com",
    phone: "(312) 555-0148",
  },
  {
    id: 18,
    name: { first: "Ravi", last: "Patel" },
    gender: "male",
    dob: { age: 38 },
    registered: { age: 6 },
    location: { city: "London" },
    nat: "GB",
    email: "ravi.patel@example.co.uk",
    phone: "+44 20 7946 0637",
  },
  {
    id: 19,
    name: { first: "Sophie", last: "Dubois" },
    gender: "female",
    dob: { age: 27 },
    registered: { age: 2 },
    location: { city: "Paris" },
    nat: "FR",
    email: "sophie.dubois@example.fr",
    phone: "+33 1 2345 6789",
  },
  {
    id: 20,
    name: { first: "Tobias", last: "Müller" },
    gender: "male",
    dob: { age: 35 },
    registered: { age: 7 },
    location: { city: "Vienna" },
    nat: "AT",
    email: "tobias.mueller@example.at",
    phone: "+43 1 2345678",
  },
];
